### ISSUE TITLE
Accept translations in any language

### ISSUE THREAD

**Issue by unaizalakain** [SectorLabs/django-localized-fields#19]
I'm working on a project which requires localized fields to be in at least one language, but this could be any language. This use case is provided out of the box by `django.forms.fields.MultiValueField` by combining `required=True` and `require_all_fields=False`. django-localized-fields makes this hard though:

- If the field form is given `required=True`, it marks the default language as mandatory in `localized_fields.forms.LocalizedFieldForm.__init__`.

- If the field is given `null=False` (which makes sense if you are expecting translations in at least one language) it checks that the default language has a translation in `localized_fields.fields.field.LocalizedField.validate`.

I think this introduces an arbitrary limitation. If the feature of marking some concrete translations as required is needed, the form field could just accept a list with the required languages, `required=True` would then just make the root multi value form field required (which means that any translation would suffice) and if `null=False` the field would just validate that at least one translation exists.

**Comment by Photonios** [comment]
Maybe this helps:

http://django-postgres-extra.readthedocs.io/hstore/#not-null-constraint

This package uses `django-postgres-extra`. You can specify a list of languages to be required. If correctly, this should be a small change in `django-localized-field`.

**Comment by unaizalakain** [comment]
From what I understand, that doesn't work for fields which are required to be filled in in at least one language and when that language can be any language.

**Comment by seroy** [comment]
I agree with @unaizalakain, currently `django-localized-fields` can not be used in case when translation required for any language. 
In my opinion, it will be great if `django-localized-fields` will be cover all use cases:

1. Optional filling `(blank=True, null=True, required=[])`
2. Translation required for any language `(blank=False, null=False, required=[])`
3. Translation required for specific languages `(blank=False, null=False, required=['en', 'ro'])`
4. Translation required for all languages `(blank=False, null=False, required=True)`

Possible, for backward compatibility, `LocalizedField` (by default (when `blank=False`, `null=False` and `required` not passed)) make the primary language required and the others optional (it case 3).

`required` parameter in `HStoreField` already implements constraint enforced on a database level, but additionaly need implement field and form field validation, pass `required` attribute for widgets and so on. 
All of this require  to change `LocalizedField` class (`validate` method, `formfield`, ...) and `LocalizedFieldForm` class. And of course write tests.

**Comment by unaizalakain** [comment]
That would indeed satisfy this use case.

As both `blank` and `required` operate on the same dimension, the only drawback I see is that `(blank=True, required=['en'])` is contradictory. An alternative might be accepting as a parameter to required a function `[language] -> bool` that tells whether the filled in languages are enough. It allows for logic that would otherwise require subclassing, but it's not as straightforward to use. I'm fine either way.

**Comment by Photonios** [comment]
@unaizalakain Your idea with a function that can tell whether the filling in languages are enough is hard to do since that would allow for additional validation logic that cannot easily be enforced on a database level.

I'd accept a patch that implements @seroy's proposal.

**Comment by unaizalakain** [comment]
Oh right, I forgot that this kind of validation could be done in postgresql. Forget everything I said :)

**Comment by Photonios** [comment]
@seroy @unaizalakain can you confirm PR #29 fixes this?

**Comment by unaizalakain** [comment]
Works like a charm!

**Comment by seroy** [comment]
Confirm, it works!

**Comment by Photonios** [comment]
Then I am closing this issue. Thank you both :)
