### ISSUE TITLE
Remove `required` attribute from form widget as needed

### ISSUE THREAD

**Issue by unaizalakain** [SectorLabs/django-localized-fields#21]
`AdminLocalizedFieldWidget` removes the `required` attribute if the widget has `is_required` set to false. Is there a reason why we shouldn't do this for `LocalizedFieldWidget` too?

**Comment by Photonios** [comment]
@seroy You can probably better answer this :-)

**Comment by seroy** [comment]
`AdminLocalizedFieldWidget` handle `required` attribute more gently (is especially make sense with FileInput widget). So is no reason why `LocalizedFieldWidget` shouldn't do this too.
