### ISSUE TITLE
Add a language label to localized subwidgets

### ISSUE THREAD

**Issue by unaizalakain** [SectorLabs/django-localized-fields#25]
As far as I can tell, and although the admin widget shows each subwidget's language, the default formfield doesn't. I think it would be nice to have.

**Comment by Photonios** [comment]
I've noticed this too. This would indeed be nice to have.

**Comment by unaizalakain** [comment]
Would a solution like https://github.com/SectorLabs/django-localized-fields/compare/master...unaizalakain:labels be acceptable?

**Comment by Photonios** [comment]
That would definitely be acceptable. If you can fix the one-letter variables, I'd merge it :)

**Comment by Photonios** [comment]
Actually, I've taken the liberty of pulling in your commit :) See PR #30
