### ISSUE TITLE
Using LocalizedUniqueSlugField returns 404

### ISSUE THREAD

**Issue by mansonul** [SectorLabs/django-localized-fields#48]
Hi,

I have this code:

models.py
```
class Event(LocalizedModel, models.Model):
    event_title = LocalizedCharField(_('Event Title'), max_length=256)
    event_slug = LocalizedUniqueSlugField(populate_from='event_title')
```

views.py
```
class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'
    slug_field = 'event_slug'
    slug_url_kwarg = 'event_slug'
```

urls.py
```
urlpatterns += i18n_patterns(
    url(r'^(?P<event_slug>[\w\-]+)/$', EventDetailView.as_view(), name='event-detail')
)
```

When I try to access localhost:8000/en/test (where test is a valid slug) I get a 404 page.
Django toolbar shows this:

SELECT "events_event"."id", "events_event"."event_title", "events_event"."event_slug" FROM "events_event" WHERE "events_event"."event_slug" = NULL

Could you tell me what I'm doing wrong?
Thank you!

Using django 1.11.10

**Comment by Photonios** [comment]
I guess you should be filtering on `event_slug__en` (one of the keys)
