### ISSUE TITLE
Translation required for any language leads to default language constraint

### ISSUE THREAD

**Issue by sliverc** [SectorLabs/django-localized-fields#58]
Using following model:

```python
class Test(models.Model):
  name = LocalizedField(blank=False, null=False, required=False)
```

leads to following migration:
```python
migrations.CreateModel(
      name="Test",
      fields=[
          ("name", localized_fields.fields.field.LocalizedField(required=["en"])),
      ],
      options={"abstract": False},
  ),
```

This migration then will create a constraint that English is required and not just any language as stated in documentation.

**Comment by Photonios** [comment]
Fixed in `django-postgres-extra` v1.21a16, which is part of `django-localized-fields` v5.0a9 release.

https://github.com/SectorLabs/django-localized-fields/releases/tag/v5.0a9
https://github.com/SectorLabs/django-postgres-extra/releases/tag/v1.21a16
