### ISSUE TITLE
CI Fails with some SystemCheckError

### ISSUE THREAD

**Issue by GabLeRoux** [SectorLabs/django-localized-fields#63]
Hey there, I configured travis so it runs everything as soon as I fork a project. [I submitted a very small change (unrelated to code)](https://github.com/SectorLabs/django-localized-fields/pull/62) and [CI fails with following error](https://travis-ci.com/GabLeRoux/django-localized-fields/builds/109300188):

```
SystemCheckError: System check identified some issues:
ERRORS:
?: (admin.E403) A 'django.template.backends.django.DjangoTemplates' instance must be configured in TEMPLATES in order to use the admin application.
?: (admin.E406) 'django.contrib.messages' must be in INSTALLED_APPS in order to use the admin application.
?: (admin.E407) 'django.contrib.sessions' must be in INSTALLED_APPS in order to use the admin application.
?: (admin.E408) 'django.contrib.auth.middleware.AuthenticationMiddleware' must be in MIDDLEWARE in order to use the admin application.
?: (admin.E409) 'django.contrib.messages.middleware.MessageMiddleware' must be in MIDDLEWARE in order to use the admin application.
System check identified 5 issues (0 silenced).
The command "coverage run manage.py test" exited with 1.
```

I wonder if it's possible to make it succeed by default without any configuration 👍 

I just took a second look and I see there are both travis and circleci, any reason why? Maybe you should drop support from one or the other. I see there's a circleci badge, but no travis badge in the readme.

**Comment by GabLeRoux** [comment]
@Photonios bump

**Comment by Photonios** [comment]
I have removed the broken TravisCI configuration. It is not used :) CircleCI is the actual Ci being used. Hope this helps!
