### ISSUE TITLE
Add documentation about creating the hstore extenstion in the db

### ISSUE THREAD

**Issue by atleta** [SectorLabs/django-localized-fields#64]
Hi,

In order to start using your app, one has to somehow add the hstore extension. Now, since you are using django-postgres-extras, it will try to do so by itself (and fail in most cases). django-postgres-extras has some instructions in their README, but I have described a better, more convenient way of doing it here: https://github.com/SectorLabs/django-postgres-extra/issues/80 .

  Regards,
    Laszlo

**Comment by Photonios** [comment]
See my reply in SectorLabs/django-postgres-extra#80 

It should happpen automatically. If it doesn't, it'll have to be fixed :) I'll close this issue now since this would be a django-postgres-extra issue and not a django-localized-fields issue.
