### ISSUE TITLE
IntegrityError even when removing the uniqueness constraint

### ISSUE THREAD

**Issue by maxthevoice** [SectorLabs/django-localized-fields#69]
I previously created a migration to add uniqueness constraint but I had issue when creating instance with empty value when another exists with the same empty value, ei:

```json
{
    "en": "foo",
    "fr": ""
}
```

The error looked like:

```txt
IntegrityError:
duplicate key value violates unique constraint "controls_questionchoicelist_name_unique_fr"
DETAIL:  Key ((name -> 'fr'::text))=() already exists.
```
Then, I decided to remove the unique constraint, but even if the migration went successfuly, the error was throwing anyway. 

```diff
-name = LocalizedCharField(blank=False, null=False, required=False, uniqueness=get_language_codes())
+name = LocalizedCharField(blank=False, null=False, required=False)
```

I had to delete it mannually in my DB. I think this is an issue that could be fixed.

But about my first issue, related to the error, there is a way to prevent empty value to be flag as a duplicate?

**Comment by Photonios** [comment]
I just tried this and it seems to work fine. It correctly drops the constraint. Please make sure you are using the latest version of django-postgres-extra.

Feel free to re-open the issue if you still experience issues.
