### ISSUE TITLE
django-postgresql-extra dependency breaks python 3.5 & 3.6 compatibility

### ISSUE THREAD

**Issue by atleta** [SectorLabs/django-localized-fields#71]
django-postgresql-extra has released 2 (alpha) versions on PyPI and they require python 3.7+. If you don't need v2 of their package (which is likely the case) then please consider pinning the dependency as "<2.0" as now it breaks installations on python<3.7

**Comment by Photonios** [comment]
Ive fixed the incompatibility. Could you try again?

**Comment by atleta** [comment]
The changes say "Pin django-postgres-extra dependency down to <2.0", but you have  >=2.0a, <3.0 in the setup.py file.

**Comment by Photonios** [comment]
That's for the unreleased 6.0 version.

I made another commit on the v5.x branch: https://github.com/SectorLabs/django-localized-fields/commit/dad7f164cdf965ea673f483277aaf66bc5c93200
