### ISSUE TITLE
Feature: ContextManager returning translated values

### ISSUE THREAD

**Issue by sbor23** [SectorLabs/django-localized-fields#76]
I would be cool if there was a utility ContextManager that would evaluate every `LocalizedValue` directly to the active language (or an override language if specified) to it's translated value.

So the usage could be something like this:

```python
def collect_fields():
    # collect some data from different models with LocalizedFields
    pass

with LocalizedValue.get_translations(optional_language_string):
    my_fields = collect_fields()
```

This is inspired by the Django translation override ContextManager:
https://docs.djangoproject.com/en/3.0/ref/utils/#django.utils.translation.override

**Comment by Photonios** [comment]
This already works with Django's `django.utils.translation.override`. There should be no need for a separate contect manager.
