### ISSUE TITLE
Query filter using hyphen in the field name  

### ISSUE THREAD

**Issue by gnud** [SectorLabs/django-localized-fields#79]
if the LANGUAGE_CODE is set to 'en-us'.

I don't know an option to write the field name as seen bellow:

`models.Person.objects.filter(title__en-us='Bob')`

this will cause a Python syntax error.

How to deal with such a situation?
- if possible to be added in the documentation :) as well.

**Comment by belkka** [comment]
```
func(**{'arbitrary string with spaces and -hyphens-': 'Bob'})
```

Currently there is an example of using such a technique

![image](https://user-images.githubusercontent.com/16609579/77914202-3c486c80-729e-11ea-8e64-3c3c0b8ece6c.png)

https://django-localized-fields.readthedocs.io/en/latest/filtering.html#specific-language

**Comment by Photonios** [comment]
This is not a question specific to `django-localized-fields`, but more to Django itself. The `__` syntax is quite common in Django.

@belkka Thanks for answering this. Your answer is correct.
